name: landina_coupon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  assorted_layout_widgets: ^7.0.0
  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  iconly: ^1.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  ionicons: ^0.2.1
  json_annotation: ^4.7.0
  readmore: ^2.2.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/landina-logo.png"

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad/Estedad-Thin.ttf
          weight: 100
        - asset: assets/fonts/Estedad/Estedad-Light.ttf
          weight: 200
        - asset: assets/fonts/Estedad/Estedad-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Estedad/Estedad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad/Estedad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Estedad/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad/Estedad-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Estedad/Estedad-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/fonts/
    - assets/svg/
    - assets/images/
