// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqLo1cmOyKpb6wYj5KX8-7RjRCYeZQxZU',
    appId: '1:629123764170:web:23fc1d5a0eb25dee240933',
    messagingSenderId: '629123764170',
    projectId: 'landina-coupon',
    authDomain: 'landina-coupon.firebaseapp.com',
    storageBucket: 'landina-coupon.appspot.com',
    measurementId: 'G-QS5R33LPLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qNPea4gG2xypAPpT8jv3aoLBEUjir0M',
    appId: '1:629123764170:android:c23cea0d95272deb240933',
    messagingSenderId: '629123764170',
    projectId: 'landina-coupon',
    storageBucket: 'landina-coupon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxL3HgDcFqBDl9LGOCoc2D1DPEIsxOoQI',
    appId: '1:629123764170:ios:ca828f6f3a48eb90240933',
    messagingSenderId: '629123764170',
    projectId: 'landina-coupon',
    storageBucket: 'landina-coupon.appspot.com',
    iosClientId: '629123764170-l4dkmfecmra5ugoo9hri5nh2vtl8jvua.apps.googleusercontent.com',
    iosBundleId: 'co.landina.coupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxL3HgDcFqBDl9LGOCoc2D1DPEIsxOoQI',
    appId: '1:629123764170:ios:bec85140bab5a021240933',
    messagingSenderId: '629123764170',
    projectId: 'landina-coupon',
    storageBucket: 'landina-coupon.appspot.com',
    iosClientId: '629123764170-87sf8s22vpik917sbtv22u4qspll0fq4.apps.googleusercontent.com',
    iosBundleId: 'co.coupon.landina',
  );
}
